apiVersion: v1
kind: Service
metadata:
  name: {{ include "rise-app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rise-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rise-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.rise.deployment.httpPort }}
      targetPort: http
      protocol: TCP
